import {
  AlertCircle,
  DoorOpen,
  FileLock,
  FileSearch,
  KeyRound,
  Loader2,
  PackageOpen,
  Workflow,
} from "lucide-react";

import type { Agent3Result } from "@/api/stage-results";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import { Mono } from "./common";

interface Props {
  result?: Agent3Result;
  isComplete: boolean;
}

const SECTION_META: Array<{
  key: keyof Omit<Agent3Result["sections"], "files_of_interest">;
  label: string;
  icon: React.ReactNode;
}> = [
  { key: "initial_access",    label: "Initial access",    icon: <DoorOpen   className="h-4 w-4" /> },
  { key: "execution_chain",   label: "Execution chain",   icon: <Workflow   className="h-4 w-4" /> },
  { key: "persistence",       label: "Persistence",       icon: <FileLock   className="h-4 w-4" /> },
  { key: "credential_access", label: "Credential access", icon: <KeyRound   className="h-4 w-4" /> },
  { key: "staging",           label: "Staging",           icon: <PackageOpen className="h-4 w-4" /> },
];

export function ReportPanel({ result, isComplete }: Props) {
  if (!result) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Incident report</CardTitle>
          <CardDescription>
            Generated by Agent 3 once the pipeline finishes.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isComplete ? (
            <div className="flex items-start gap-2 text-sm">
              <AlertCircle className="h-4 w-4 mt-0.5 text-yellow-500" />
              No report data was received.
            </div>
          ) : (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" /> Waiting for the
              report writer to finish...
            </div>
          )}
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between gap-3 flex-wrap">
          <div>
            <CardTitle className="text-xl">Incident report</CardTitle>
            <CardDescription>Case: <Mono>{result.case}</Mono></CardDescription>
          </div>
          <OverallConfidence value={result.confidence_overall} />
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* exec summary */}
        <div className="rounded-md border border-primary/30 bg-primary/5 p-4">
          <div className="text-[11px] uppercase tracking-wide text-primary font-semibold mb-1">
            Executive summary
          </div>
          <p className="text-sm leading-relaxed">{result.summary}</p>
        </div>

        {/* 5 narrative sections */}
        <div className="space-y-4">
          {SECTION_META.map((meta) => (
            <Section
              key={meta.key}
              icon={meta.icon}
              title={meta.label}
              body={result.sections[meta.key]}
            />
          ))}
        </div>

        {/* files of interest */}
        <Section
          icon={<FileSearch className="h-4 w-4" />}
          title="Files of interest"
          body={
            <ul className="space-y-1">
              {result.sections.files_of_interest.map((f) => (
                <li key={f}><Mono>{f}</Mono></li>
              ))}
            </ul>
          }
        />
      </CardContent>
    </Card>
  );
}

function Section({
  icon,
  title,
  body,
}: {
  icon: React.ReactNode;
  title: string;
  body: React.ReactNode;
}) {
  return (
    <section>
      <h3 className="flex items-center gap-2 text-sm font-medium mb-1.5">
        <span className="text-primary">{icon}</span>
        {title}
      </h3>
      <div className="text-sm leading-relaxed text-foreground/90 pl-6">
        {typeof body === "string" ? <p>{body}</p> : body}
      </div>
    </section>
  );
}

function OverallConfidence({ value }: { value: number }) {
  const pct = Math.round(Math.max(0, Math.min(1, value)) * 100);
  const variant: "success" | "warning" | "destructive" =
    pct >= 80 ? "success" : pct >= 50 ? "warning" : "destructive";
  return (
    <div className="flex items-center gap-2">
      <span className="text-[11px] uppercase tracking-wide text-muted-foreground">
        Overall confidence
      </span>
      <Badge variant={variant} className="tabular-nums">{pct}%</Badge>
    </div>
  );
}
